FROM node:24-alpine AS base
ARG UID=1000
ARG GID=1000
RUN apk add --no-cache libc6-compat brotli gzip zstd parallel pnpm
WORKDIR /app
RUN if ! getent group ${GID} >/dev/null 2>&1; then addgroup -g ${GID} appuser; fi
RUN if ! getent passwd ${UID} >/dev/null 2>&1; then adduser -D -u ${UID} -G $(getent group ${GID} | cut -d: -f1) appuser; fi
RUN chown -R ${UID}:${GID} /app
USER ${UID}:${GID}
COPY package.json pnpm-lock.yaml tsconfig.json ./
#without setting this env, TTY is required, and pnpm install fails: ERR_PNPM_ABORTED_REMOVE_MODULES_DIR_NO_TTY
ENV CI=true
#documentation, do not forget to set these volumes
VOLUME ["/app/src", "/app/static", "/app/node_modules"]
ENTRYPOINT ["sh", "-c", "pnpm install --no-frozen-lockfile && pnpm run dev"]