FROM node:20-alpine AS base

WORKDIR /app

RUN apk --no-cache add curl

RUN curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

CMD ["pnpm", "hmr"]
