version: "3.9"

services:

  auth:
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:${TAG_IMAGE:-latest}
    build: ./fastauth
    restart: always
    env_file:
      - ${BASE_PATH:-.}/fastauth/.env
    ports:
      - "9081:9081"
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: ghcr.io/flatfeestack/flatfeestack/backend:${TAG_IMAGE:-latest}
    build: ./backend
    restart: always
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    ports:
      - "9082:9082"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy

  analysis-engine:
    image: ghcr.io/flatfeestack/flatfeestack/analysis-engine:${TAG_IMAGE:-latest}
    build: ./analysis-engine
    restart: always
    env_file:
      - ${BASE_PATH:-.}/analysis-engine/.env
    volumes:
      - ${BASE_PATH:-.}/.repos:/app/repos
    ports:
      - "9083:9083"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  payout:
    image: ghcr.io/flatfeestack/flatfeestack/payout:${TAG_IMAGE:-latest}
    build: ./payout
    restart: always
    env_file:
      - ${BASE_PATH:-.}/payout/.env
    ports:
      - "9084:9084"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  frontend:
    image: ghcr.io/flatfeestack/flatfeestack/frontend:${TAG_IMAGE:-latest}
    build: ./frontend
    ports:
      - "9085:9085"

  db:
    image: postgres:15-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    image: ghcr.io/flatfeestack/flatfeestack/caddy:${TAG_IMAGE:-latest}
    build: ./caddy
    ports:
      - "8080:8080"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  openethereum:
    #https://stackoverflow.com/questions/30233105/docker-compose-up-for-only-certain-containers
    #profiles: [ "local" ]
    #https://github.com/ledgerwatch/erigon/blob/devel/DEV_CHAIN.md
    image: openethereum/openethereum:v3.1.1
    ports:
      - "8545:8545"
    user: root
    volumes:
      - ${BASE_PATH:-.}/.chain:/tmp/chain
    command: --chain=dev --jsonrpc-interface=all --jsonrpc-hosts=all --jsonrpc-apis=all --jsonrpc-cors='*' --base-path=/tmp/chain
