version: "3"

services:

  reverse-proxy:
    container_name: flatfeestack-caddy
    image: caddy:2-alpine
    networks:
      - prod
      - test
    volumes:
      - ./Caddyfile.deploy:/etc/caddy/Caddyfile
      - ${CADDY_DATA_LOCAL_DIR}:/data
    ports:
      - 80:80
      - 443:443

networks:
  test: