version: "3.9"

services:

  auth:
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:${TAG_IMAGE:-latest}
    build: ./fastauth
    configs:
      - source: auth_env
        target: /home/nonroot/.env
    depends_on:
      - db

  backend:
    image: ghcr.io/flatfeestack/flatfeestack/backend:${TAG_IMAGE:-latest}
    build: ./backend
    configs:
      - source: backend_env
        target: /app/.env
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      - db

  analysis-engine:
    image: ghcr.io/flatfeestack/flatfeestack/analysis-engine:${TAG_IMAGE:-latest}
    volumes:
      - ./.repos:/app/repos
    build: ./analysis-engine
    configs:
      - source: analysis_env
        target: /app/.env
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  payout:
    image: ghcr.io/flatfeestack/flatfeestack/payout:${TAG_IMAGE:-latest}
    build: ./payout
    configs:
      - source: payout_env
        target: /home/nonroot/.env
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  #payout-nodejs:
  #  image: ghcr.io/flatfeestack/flatfeestack/payout-nodejs:${TAG_IMAGE:-latest}
  #  build: ./payout-nodejs
  #  ports:
  #    - 9086:9086
  #  extra_hosts:
  #    - ${EXTRA_HOSTS:-localhost:127.0.0.1}
  #  env_file:
  #    payout-nodejs/.env
  #  depends_on:
  #    - flextesa

  frontend:
    image: ghcr.io/flatfeestack/flatfeestack/frontend:${TAG_IMAGE:-latest}
    build: ./frontend

  db:
    image: postgres:14-alpine
    configs:
      - source: db_env
        target: /docker-entrypoint-initdb.d/0-init.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s

  reverse-proxy:
    image: caddy:2-alpine
    configs:
      - source: caddy_env
        target: /etc/caddy/Caddyfile
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

configs:
  auth_env:
    file: fastauth/.env
  backend_env:
    file: backend/.env
  analysis_env:
    file: analysis-engine/.env
  payout_env:
    file: payout/.env
  db_env:
    file: .env
  caddy_env:
    file: Caddyfile

  # https://assets.tqtezos.com/docs/setup/2-sandbox/
  #flextesa:
  #  image: tqtezos/flextesa:20211206
  #  environment:
  #    - block_time=15
  #  ports:
  #    - 20000:20000
  #  command: hangzbox start
