version: "3.9"

services:

  auth:
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:${TAG_IMAGE:-latest}
    build: ./fastauth
    restart: always
    env_file:
      - ${BASE_PATH:-.}/fastauth/.env
    ports:
      - "9081:9081"
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: ghcr.io/flatfeestack/flatfeestack/backend:${TAG_IMAGE:-latest}
    build: ./backend
    restart: always
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    ports:
      - "9082:9082"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy

  analysis-engine:
    image: ghcr.io/flatfeestack/flatfeestack/analysis-engine:${TAG_IMAGE:-latest}
    build: ./analysis-engine
    restart: always
    env_file:
      - ${BASE_PATH:-.}/analysis-engine/.env
    volumes:
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  payout:
    image: ghcr.io/flatfeestack/flatfeestack/payout:${TAG_IMAGE:-latest}
    build: ./payout
    restart: always
    env_file:
      - ${BASE_PATH:-.}/payout/.env
    ports:
      - "9084:9084"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  frontend:
    image: ghcr.io/flatfeestack/flatfeestack/frontend:${TAG_IMAGE:-latest}
    build: ./frontend
    ports:
      - "9085:9085"

  db:
    image: postgres:15-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    image: ghcr.io/flatfeestack/flatfeestack/caddy:${TAG_IMAGE:-latest}
    build: ./caddy
    ports:
      - "8080:8080"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  ganache:
    #https://stackoverflow.com/questions/30233105/docker-compose-up-for-only-certain-containers
    #profiles: [ "local" ]
    build: ./ganache
    ports:
      - "8545:8545"
    volumes:
      - ${BASE_PATH:-.}/.chain:/tmp/chain
    command: --database.dbPath=/tmp/chain --miner.blockTime=15 --wallet.seed="test" --server.host="0.0.0.0" --miner.timestampIncrement=15 --chain.networkId=1337

    #I tried geth, but geth does not support eth_mine and eth_increaseTime. There is a pull request, that would solve
    #it, but its not going to be included anytime soon: https://github.com/ethereum/go-ethereum/pull/16834
    #libfaketime does not work with golang: https://github.com/wolfcw/libfaketime/issues/195
    #command: --dev --dev.period=2 --http --http.api=eth,web3,personal,net --http.corsdomain="http://remix.ethereum.org" --datadir=/tmp/chain --http.addr=0.0.0.0 --mine --miner.threads=1 --miner.noverify
