version: "3"

services:

  auth:
    container_name: flatfeestack-auth
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:${TAG_IMAGE:-latest}
    build: ./fastauth
    ports:
      - 9081:9081
    env_file:
      - fastauth/.env
    depends_on:
      - db

  backend:
    container_name: flatfeestack-backend
    image: ghcr.io/flatfeestack/flatfeestack/backend:${TAG_IMAGE:-latest}
    build: ./backend
    ports:
      - 9082:9082
    env_file:
      - backend/.env
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      - db

  analysis-engine:
    container_name: flatfeestack-analysis-engine
    image: ghcr.io/flatfeestack/flatfeestack/analysis-engine:${TAG_IMAGE:-latest}
    build: ./analysis-engine
    ports:
      - 9083:9083
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    env_file:
      - analysis-engine/.env

  payout:
    container_name: flatfeestack-payout
    image: ghcr.io/flatfeestack/flatfeestack/payout:${TAG_IMAGE:-latest}
    build: ./payout
    ports:
      - 9084:9084
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      - openethereum
      - payout-nodejs
    env_file:
      - payout/.env

  payout-nodejs:
    container_name: flatfeestack-payout-nodejs
    image: ghcr.io/flatfeestack/flatfeestack/payout-nodejs:${TAG_IMAGE:-latest}
    build: ./payout-nodejs
    ports:
      - 9086:9086
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    env_file:
      payout-nodejs/.env

  frontend:
    container_name: flatfeestack-frontend
    image: ghcr.io/flatfeestack/flatfeestack/frontend:${TAG_IMAGE:-latest}
    build: ./frontend
    ports:
      - 9085:9085

  db:
    container_name: flatfeestack-db
    image: postgres:13-alpine
    volumes:
      - ./.db:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/0-init.sql
      - ./fastauth/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flatfeestack

  reverse-proxy:
    container_name: flatfeestack-caddy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    ports:
      - 80:80

  #https://openethereum.wiki/Private-development-chain/
  openethereum:
    container_name: flatfeestack-openethereum
    image: openethereum/openethereum:v3.1.1
    ports:
      - 8545:8545
      - 8546:8546
    user: root
    volumes:
      - ./.chain:/tmp/chain
    command: --chain=dev --jsonrpc-interface=all --jsonrpc-hosts=all --jsonrpc-apis=all --jsonrpc-cors='*' --base-path=/tmp/chain
