version: "3"

volumes:
  caddy_data:
  postgres_data:

services:
  web:
    container_name: flatfeestack-frontend
    build: ./frontend

  auth:
    container_name: flatfeestack-auth
    build: ./auth
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - DEV=test
      - USERS=tom:pw1;ile:pw2;Sevi:1234

  analysis-engine:
    container_name: flatfeestack-analysis-engine
    build:
      context: ./analysis-engine
      dockerfile: ../Dockerfile-analysis
    ports:
      - "7000:8080"

  postgres:
    image: postgres:alpine
    container_name: flatfeestack-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  caddy:
    container_name: "flatfeestack-caddy"
    build: ./caddy
    volumes:
      - caddy_data:/root/.caddy # to save certificates on disk
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - analysis-engine
      - auth
