version: "3.9"

services:
  auth:
    build: ./fastauth
    env_file:
      - ${BASE_PATH:-.}/fastauth/.env
    ports:
      - "9081:9081"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    ports:
      - "9082:9082"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy

  forum:
    build: ./forum
    env_file:
      - ${BASE_PATH:-.}/forum/.env
    ports:
      - "9086:9086"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  analyzer:
    build: ./analyzer
    env_file:
      - ${BASE_PATH:-.}/analyzer/.env
    volumes:
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  payout:
    build: ./payout
    env_file:
      - ${BASE_PATH:-.}/payout/.env
    ports:
      - "9084:9084"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ${BASE_PATH:-.}/frontend:/app
    ports:
      - "9085:9085"

  db:
    image: postgres:16-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    build: ./caddy
    ports:
      - "8080:8080"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  local-blockchain:
    build: ./smart-contracts-eth
    ports:
      - "8545:8545"

  stripe-webhook:
    build: ./stripe
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
