version: "3"

volumes:
  caddy_data:
  postgres_data:

services:
  web:
    container_name: flatfeestack-frontend
    build: ./frontend

  auth:
    container_name: flatfeestack-auth
    build: ./fastauth
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - DEV=test
      - USERS=tom:pw1;ile:pw2;Sevi:1234
      - REFRESH_COOKIE_PATH=/auth/refresh

  analysis-engine:
    container_name: flatfeestack-analysis-engine
    build: ./analysis-engine
    ports:
      - "7000:8080"

  api:
    container_name: flatfeestack-api
    build: ./api
    ports:
      - "6000:8080"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: flatfeestack-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  caddy:
    container_name: "flatfeestack-caddy"
    build: ./caddy
    volumes:
      - caddy_data:/root/.caddy # to save certificates on disk
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
