version: "3.9"

services:

  auth:
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:${TAG_IMAGE:-latest}
    build: ./fastauth
    restart: always
    env_file:
      - ${BASE_PATH:-.}/fastauth/.env
    ports:
      - "9081:9081"
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - platform

  backend:
    image: ghcr.io/flatfeestack/flatfeestack/backend:${TAG_IMAGE:-latest}
    build: ./backend
    restart: always
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    ports:
      - "9082:9082"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - platform

  analyzer:
    image: ghcr.io/flatfeestack/flatfeestack/analyzer:${TAG_IMAGE:-latest}
    build: ./analyzer
    restart: always
    env_file:
      - ${BASE_PATH:-.}/analyzer/.env
    volumes:
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    profiles:
      - platform

  payout:
    image: ghcr.io/flatfeestack/flatfeestack/payout:${TAG_IMAGE:-latest}
    build: ./payout
    restart: always
    env_file:
      - ${BASE_PATH:-.}/payout/.env
    ports:
      - "9084:9084"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    profiles:
      - platform

  frontend:
    image: ghcr.io/flatfeestack/flatfeestack/frontend:${TAG_IMAGE:-latest}
    build: ./frontend
    ports:
      - "9085:9085"
    profiles:
      - platform
      - smart-contracts-eth

  db:
    image: postgres:15-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30
    profiles:
      - blockscout
      - platform

  caddy:
    image: ghcr.io/flatfeestack/flatfeestack/caddy:${TAG_IMAGE:-latest}
    build: ./caddy
    ports:
      - "8080:8080"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    profiles:
      - platform

  blockscout:
    command: "bash -c \"bin/blockscout eval \\\"Elixir.Explorer.ReleaseTasks.create_and_migrate()\\\" && bin/blockscout start\""
    depends_on:
      - db
      - redis
    environment:
      ACCOUNT_CLOAK_KEY: ~
      ACCOUNT_ENABLED: false
      ACCOUNT_REDIS_URL: "redis://redis:6379"
      ALLOWED_EVM_VERSIONS: "homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,default"
      API_PATH: /
      API_RATE_LIMIT: 50
      API_RATE_LIMIT_BY_IP: 50
      API_RATE_LIMIT_BY_KEY: 50
      API_RATE_LIMIT_STATIC_API_KEY: ~
      API_RATE_LIMIT_WHITELISTED_IPS: ~
      APPS_MENU: true
      BLOCKSCOUT_HOST: ~
      BLOCKSCOUT_PROTOCOL: ~
      BLOCKSCOUT_VERSION: ~
      BLOCK_TRANSFORMER: base
      CACHE_ADDRESS_COUNT_PERIOD: 7200
      CACHE_ADDRESS_SUM_PERIOD: 3600
      CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD: 1800
      CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD: 1800
      CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD: 1800
      CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD: 1800
      CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: 1800
      CACHE_AVERAGE_BLOCK_PERIOD: 1800
      CACHE_BLOCK_COUNT_PERIOD: 7200
      CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL: 1800
      CACHE_MARKET_HISTORY_PERIOD: 21600
      CACHE_TOKEN_EXCHANGE_RATE_PERIOD: 1800
      CACHE_TOKEN_HOLDERS_COUNTER_PERIOD: 3600
      CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD: "3600]"
      CACHE_TOTAL_GAS_USAGE_PERIOD: 3600
      CACHE_TXS_COUNT_PERIOD: 7200
      CHAIN_ID: 1337
      CHECKSUM_ADDRESS_HASHES: true
      CHECKSUM_FUNCTION: eth
      COIN: ~
      COIN_BALANCE_HISTORY_DAYS: 90
      COIN_NAME: ~
      CUSTOM_CONTRACT_ADDRESSES_TEST_TOKEN: ~
      DATABASE_URL: "postgresql://postgres:password@db:5432/blockscout?ssl=false"
      DISABLE_EXCHANGE_RATES: true
      DISABLE_INDEXER: false
      DISABLE_KNOWN_TOKENS: false
      DISABLE_READ_API: false
      DISABLE_REALTIME_INDEXER: false
      DISABLE_TOKEN_INSTANCE_FETCHER: false
      DISABLE_WEBAPP: false
      DISABLE_WRITE_API: false
      DISPLAY_TOKEN_ICONS: false
      ECTO_USE_SSL: false
      EMISSION_FORMAT: DEFAULT
      ENABLE_RUST_VERIFICATION_SERVICE: true
      ENABLE_SOURCIFY_INTEGRATION: false
      ENABLE_TXS_STATS: true
      ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: false
      ETHEREUM_JSONRPC_HTTP_URL: "http://ganache:8545/"
      ETHEREUM_JSONRPC_TRACE_URL: "http://ganache:8545/"
      ETHEREUM_JSONRPC_TRANSPORT: http
      ETHEREUM_JSONRPC_VARIANT: ganache
      ETHEREUM_JSONRPC_WS_URL: "ws://ganache:8545/"
      EXCHANGE_RATES_COIN: ~
      EXTERNAL_APPS: "[]"
      FETCH_REWARDS_WAY: trace_block
      HEART_BEAT_TIMEOUT: 30
      HIDE_BLOCK_MINER: false
      HISTORY_FETCH_INTERVAL: 30
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      IPC_PATH: ~
      JSON_RPC: ~
      LINK_TO_OTHER_EXPLORERS: false
      LOGO: /images/blockscout_logo.svg
      LOGO_FOOTER: /images/blockscout_logo.svg
      MAINTENANCE_ALERT_MESSAGE: ~
      MAX_SIZE_UNLESS_HIDE_ARRAY: 50
      MAX_STRING_LENGTH_WITHOUT_TRIMMING: 2040
      NETWORK: ~
      NETWORK_PATH: /
      OTHER_EXPLORERS: "{}"
      POOL_SIZE: 10
      POOL_SIZE_API: 0
      PORT: 4000
      RELEASE_LINK: ~
      RE_CAPTCHA_CLIENT_KEY: ~
      RE_CAPTCHA_SECRET_KEY: ~
      SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
      SHOW_ADDRESS_MARKETCAP_PERCENTAGE: true
      SHOW_MAINTENANCE_ALERT: false
      SHOW_PRICE_CHART: false
      SHOW_TENDERLY_LINK: false
      SHOW_TXS_CHART: true
      SOCKET_ROOT: /
      SOURCIFY_REPO_URL: ~
      SOURCIFY_SERVER_URL: ~
      SUBNETWORK: "Awesome chain"
      SUPPORTED_CHAINS: "{}"
      TENDERLY_CHAIN_PATH: ~
      TOKEN_METADATA_UPDATE_INTERVAL: 172800
      TXS_HISTORIAN_INIT_LAG: 0
      TXS_STATS_DAYS_TO_COMPILE_AT_INIT: 10
      UNCLES_IN_AVERAGE_BLOCK_TIME: false
      WOBSERVER_ENABLED: false
    image: blockscout/blockscout
    ports:
      - "4000:4000"
    volumes:
      - "blockscout_logs:/app/logs/"
    profiles:
      - blockscout

  ganache:
    command: '--database.dbPath "/ganache" --logging.verbose --wallet.accounts "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,100000000000000000000" --wallet.accounts "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,100000000000000000000" --wallet.accounts "0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1,100000000000000000000" --wallet.accounts "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e,100000000000000000000" -b 12 --miner.timestampIncrement "12"'
    image: "trufflesuite/ganache:v7.7.7"
    ports:
      - "8545:8545"
    volumes:
      - "ganache:/ganache"
    profiles:
      - smart-contracts-eth

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    profiles:
      - blockscout

volumes:
  blockscout_logs: ~
  ganache: ~
  postgres: ~
  redis: ~
