version: "3.9"

services:
  auth:
    build: ./fastauth
    env_file:
      - ${BASE_PATH:-.}/fastauth/.env
    ports:
      - "9081:9081"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    ports:
      - "9082:9082"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy

  forum:
    build: ./forum
    env_file:
      - ${BASE_PATH:-.}/forum/.env
    ports:
      - "9086:9086"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  analyzer:
    build: ./analyzer
    env_file:
      - ${BASE_PATH:-.}/analyzer/.env
    volumes:
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  payout:
    build: ./payout
    env_file:
      - ${BASE_PATH:-.}/payout/.env
    ports:
      - "9084:9084"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "9085:9085"

  db:
    image: postgres:15-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    build: ./caddy
    ports:
      - "8080:8080"
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}

  blockexplorer:
    build: ./blockexplorer
    ports:
      - "3000:3000"

  ganache:
    command: '--database.dbPath "/ganache" --logging.verbose --wallet.accounts "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,100000000000000000000" --wallet.accounts "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,100000000000000000000" --wallet.accounts "0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1,100000000000000000000" --wallet.accounts "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e,100000000000000000000" -b 12 --miner.timestampIncrement "12" -h 0.0.0.0'
    image: "trufflesuite/ganache:v7.8.0"
    ports:
      - "8545:8545"
    volumes:
      - ".ganache:/ganache"

  stripe-webhook:
    build: ./stripe
    extra_hosts:
      - ${EXTRA_HOSTS:-localhost:127.0.0.1}
