services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    env_file:
      - ${BASE_PATH:-.}/auth/.env
    volumes:
      - ./auth:/app:rw,delegated
    ports:
      - "9081:9081"
      - "2342:2345"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ${BASE_PATH:-.}/backend/.env
    volumes:
      - ./backend:/app:rw,delegated
    ports:
      - "9082:9082"
      - "2340:2345"
    depends_on:
      db:
        condition: service_healthy

  forum:
    build: ./forum
    env_file:
      - ${BASE_PATH:-.}/forum/.env
    ports:
      - "9086:9086"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile.dev
    env_file:
      - ${BASE_PATH:-.}/analyzer/.env
    volumes:
      - ./analyzer:/app:rw,delegated
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
      - "2341:2345"

  frontend-svelte5:
    build:
      context: ./frontend-svelte5
      dockerfile: Dockerfile.dev
    volumes:
      - ${BASE_PATH:-.}/frontend-svelte5/src:/app/src:rw,delegated
      - ${BASE_PATH:-.}/frontend-svelte5/public:/app/public:rw,delegated
    ports:
      - "9085:3000"

  db:
    image: postgres:16-alpine
    volumes:
      - ${BASE_PATH:-.}/.db:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_PATH:-.}/db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  ganache:
    command: '--database.dbPath "/ganache" --logging.verbose --wallet.accounts "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,100000000000000000000" --wallet.accounts "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,100000000000000000000" --wallet.accounts "0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1,100000000000000000000" --wallet.accounts "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e,100000000000000000000" -b 12 --miner.timestampIncrement "12" -h 0.0.0.0'
    image: "trufflesuite/ganache:v7.9.2"
    ports:
      - "8545:8545"

  stripe-webhook:
    build: ./stripe
    volumes:
      - ${BASE_PATH:-.}/.stripe:/root/.config/stripe
    stop_grace_period: 0s

  stripe-setup:
    profiles: [setup]
    build: ./stripe
    volumes:
      - ${BASE_PATH:-.}/.stripe:/root/.config/stripe
      - ${BASE_PATH:-.}/backend/.env:/root/.env
