version: "3.9"

services:

  auth:
    ports:
      - 19081:9081

  backend:
    ports:
      - 19082:9082

  analysis-engine:
    ports:
      - 19083:9083

  payout:
    ports:
      - 19084:9084

  frontend:
    ports:
      - 19085:9085

  reverse-proxy:
    ports:
      - 8080:80

  db:
    volumes:
      - /Users/sibex/postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432

configs:
  auth_env:
    external: true
    #docker --context flatfee config create auth_env env/fastauth.env.test
  backend_env:
    external: true
    #docker --context flatfee config create backend_env env/backend.env.test
  analysis_env:
    external: true
    #docker --context flatfee config create analysis_env env/analysis-engine.env.test
  payout_env:
    external: true
    #docker --context flatfee config create payout_env env/payout.env.test
  db_env:
    external: true
    #docker --context flatfee config create db_env env/db.env.test