version: "3.9"

services:

  auth:
    ports:
      - 19081:9081

  backend:
    ports:
      - 19082:9082

  analysis-engine:
    ports:
      - 19083:9083

  payout:
    ports:
      - 19084:9084

  frontend:
    ports:
      - 19085:9085

  reverse-proxy:
    ports:
      - 8080:80

  db:
    volumes:
      - ${DATABASE_LOCAL_DIR}:/var/lib/postgresql/data
    ports:
      - 15432:5432

configs:
  auth_env:
    external: true
  backend_env:
    external: true
  analysis_env:
    external: true
  payout_env:
    external: true
  db_env:
    external: true