version: "3"

services:
  auth:
    container_name: flatfeestack-auth
    build: ./fastauth
    environment:
      - ENV=local
      - DEV=test
      - USERS=info@flatfeestack.io:pw1;jonas@flatfeestack.io:pw2;tom:pw1
      - PORT=9081
      - RS256=false
      - EDDSA=false

  backend:
    container_name: flatfeestack-backend
    build: ./backend
    environment:
      - PORT=9082
    depends_on:
      - db

  analysis-engine:
    container_name: flatfeestack-analysis-engine
    build: ./analysis-engine
    environment:
      - PORT=9083

  payout:
    container_name: flatfeestack-payout
    build: ./payout
    extra_hosts:
      - ${HOSTS}
    depends_on:
      - openethereum
    environment:
      - PORT=9084

  db:
    container_name: flatfeestack-db
    image: postgres:13-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/0-init.sql
      - ./backend/sched.sql:/docker-entrypoint-initdb.d/1-sched.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flatfeestack

  reverse-proxy:
    container_name: flatfeestack-caddy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - ${HOSTS}
    ports:
      - "80:80"

  frontend:
    container_name: flatfeestack-frontend
    build: ./frontend

  #https://openethereum.wiki/Private-development-chain/
  openethereum:
    container_name: flatfeestack-openethereum
    image: openethereum/openethereum:v3.1.1
    ports:
      - "8545:8545"
      - "8546:8546"
    command: --chain=dev --jsonrpc-interface=all --jsonrpc-hosts=all --jsonrpc-apis=all --jsonrpc-cors='*' --base-path=/tmp
