services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    env_file:
      - ${CFG_PATH:-.}/auth/.env
    volumes:
      - ./auth:/app
    ports:
      - "9081:9081"
      - "2342:2345"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ${CFG_PATH:-.}/backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "9082:9082"
      - "2340:2345"
    depends_on:
      db:
        condition: service_healthy

  forum:
    build: ./forum
    env_file:
      - ${CFG_PATH:-.}/forum/.env
    ports:
      - "9086:9086"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile.dev
    env_file:
      - ${CFG_PATH:-.}/analyzer/.env
    volumes:
      - ./analyzer:/app
      - ${BASE_PATH:-.}/.repos:/tmp/repos
    ports:
      - "9083:9083"
      - "2341:2345"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ${CFG_PATH:-.}/frontend/src:/app/src
      - ${CFG_PATH:-.}/frontend/public:/app/public
      - ${CFG_PATH:-.}/frontend/node_modules:/app/node_modules
    ports:
      - "9085:3000"

  db:
    image: postgres:18-alpine
    volumes:
      - ${CFG_PATH:-.}/.db:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    env_file:
      - ${CFG_PATH:-.}/db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 30

  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  anvil:
    image: ghcr.io/foundry-rs/foundry
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0 --block-time 12 --state /data/state.json
    volumes:
      - ${CFG_PATH:-.}/.chain/:/data
    stop_grace_period: 1s

  stripe-webhook:
    image: stripe/stripe-cli
    command: listen --skip-verify --forward-to http://backend:9082
    volumes:
      - ${CFG_PATH:-.}/.stripe:/root/.config/stripe
    stop_grace_period: 1s

  stripe-setup:
    build: ./stripe
    volumes:
      - ${CFG_PATH:-.}/.stripe:/root/.config/stripe
      - ${CFG_PATH:-.}/backend/.env:/root/.env
