version: "3"

volumes:
  caddy_data:
  postgres_data:

services:
  auth:
    container_name: flatfeestack-auth
    build: ./fastauth
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - DEV=test
      - USERS=info@flatfeestack.io:pw1;jonas@flatfeestack.io:pw2
      - REFRESH_COOKIE_PATH=/auth/refresh

  analysis-engine:
    container_name: flatfeestack-analysis-engine
    build: ./analysis-engine
    ports:
      - "7000:8080"
    environment:
      - WEBHOOK_CALLBACK_URL=${WEBHOOK_CALLBACK_URL}

  api:
    container_name: flatfeestack-api
    build: ./api
    ports:
      - "8001:8080"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - STRIPE_SECRET=${STRIPE_SECRET}
    depends_on:
      - db

  scheduler:
    container_name: flatfeestack-scheduler
    build: ./scheduler
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db

  payout:
    container_name: flatfeestack-payout
    build: ./payout
    environment:
      - ETH_PK=${ETH_PK}
      - ETH_CONTRACT=${ETH_CONTRACT}

  db:
    container_name: flatfeestack-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    container_name: "flatfeestack-caddy"
    build:
      context: frontend
    volumes:
      - caddy_data:/root/.caddy # to save certificates on disk
    ports:
      - "80:80"
      - "443:443"
