version: "3"

services:

  #######################
  # Applications:
  #######################

  test-auth:
    hostname: test-auth
    image: ghcr.io/flatfeestack/flatfeestack/fastauth:latest
    networks:
      - test
    ports:
      - 9081:9081
    env_file:
      - .test.fastauth.env
    depends_on:
      test-db:
        condition: service_healthy

  test-backend:
    hostname: test-backend
    image: ghcr.io/flatfeestack/flatfeestack/backend:latest
    networks:
      - test
    ports:
      - 9082:9082
    env_file:
      - .test.backend.env
    depends_on:
      test-db:
        condition: service_healthy

  test-analysis-engine:
    hostname: test-analysis-engine
    image: ghcr.io/flatfeestack/flatfeestack/analysis-engine:latest
    networks:
      - test
    ports:
      - 9083:9083
    env_file:
      - .test.analysis-engine.env

  test-payout:
    hostname: test-payout
    image: ghcr.io/flatfeestack/flatfeestack/payout:latest
    networks:
      - test
    ports:
      - 9084:9084
    env_file:
      - .test.payout.env

  test-frontend:
    hostname: test-frontend
    image: ghcr.io/flatfeestack/flatfeestack/frontend:latest
    networks:
      - test
    ports:
      - 9085:9085
    environment:
      - PORT=9085

  #######################
  # Infrastructure:
  #######################

  test-db:
    hostname: test-db
    image: postgres:13-alpine
    volumes:
      - ${DATABASE_LOCAL_DIR}:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/0-init.sql
      - ./fastauth/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    #https://docs.docker.com/engine/reference/builder/#healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 15
    networks:
      - test
    env_file:
      - .test.db.env

networks:
  test: