FROM golang:1.25-alpine AS base
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY db ./db
ENV TESTCONTAINERS_RYUK_DISABLED=true
RUN go test -c -o db/db_tests ./db
WORKDIR /app/db
CMD ["./db_tests", "-test.v"]
