{
 "title": "FlatFeeStack dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sponsored repositories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT repo_id) FROM sponsor_event WHERE un_sponsor_at IS NULL;"
    }
   ]
  },
  {
   "title": "New sponsored repositories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT repo_id) FROM sponsor_event WHERE un_sponsor_at IS NULL AND sponsor_at::date = CURRENT_DATE;"
    }
   ]
  },
  {
   "title": "10 most starred repositories",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT r.name, se.count\nFROM (SELECT repo_id, COUNT(*) AS count\n      FROM sponsor_event\n      WHERE un_sponsor_at IS NULL\n      GROUP BY repo_id) AS se\n         INNER JOIN repo AS r ON se.repo_id = r.id\nORDER BY se.count DESC\nLIMIT 10;"
    }
   ]
  },
  { "title": "Funds on platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total pay-ins",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT SUM(balance) / 1000000 AS value, currency as metric FROM payment_in_event WHERE status = 'SUCCESS' AND currency='USD' GROUP BY currency LIMIT 50 "
    },
    {
     "rawSql": "SELECT SUM(balance) / 1000000000000000000 AS value, currency AS metric FROM payment_in_event WHERE status = 'SUCCESS' AND currency='ETH' GROUP BY currency LIMIT 50 "
    }
   ]
  },
  {
   "title": "Distributed funds in the last week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    day,\n    currency,\n    SUM(CASE WHEN currency = 'USD' THEN balance / (10^6)\n             WHEN currency = 'GAS' THEN balance / (10^8)\n             WHEN currency = 'ETH' THEN balance / (10^18)\n             ELSE balance END) AS total_balance\nFROM\n    (\n        SELECT\n            currency,\n            balance,\n            day\n        FROM\n            daily_contribution\n        WHERE\n            day >= (CURRENT_DATE - INTERVAL '7 days')\n        \n        UNION ALL\n        \n        SELECT\n            currency,\n            balance,\n            day\n        FROM\n            future_contribution\n        WHERE\n            day >= (CURRENT_DATE - INTERVAL '7 days')\n\n    ) AS combined_contributions\nGROUP BY\n    currency,\n    day\nORDER BY\n    day;\n"
    }
   ]
  },
  {
   "title": "Funds left to distribute",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  currency,\n  SUM(\n    CASE\n      WHEN currency = 'USD' THEN balance / 1e6\n      WHEN currency = 'GAS' THEN balance / 1e8\n      WHEN currency = 'ETH' THEN balance / 1e18\n      ELSE balance\n    END\n  ) - (\n    SELECT COALESCE(SUM(\n      CASE\n        WHEN currency = 'USD' THEN balance / 1e6\n        WHEN currency = 'GAS' THEN balance / 1e8\n        WHEN currency = 'ETH' THEN balance / 1e18\n        ELSE balance\n      END\n    ), 0)\n    FROM future_contribution\n    WHERE currency = payment_in_event.currency\n  ) - (\n    SELECT COALESCE(SUM(\n      CASE\n        WHEN currency = 'USD' THEN balance / 1e6\n        WHEN currency = 'GAS' THEN balance / 1e8\n        WHEN currency = 'ETH' THEN balance / 1e18\n        ELSE balance\n      END\n    ), 0)\n    FROM daily_contribution\n    WHERE currency = payment_in_event.currency\n  ) AS \"net_balance\"\nFROM\n  payment_in_event\nWHERE\n  status = 'SUCCESS'\nGROUP BY\n  currency\n"
    }
   ]
  },
  {
   "title": "Distributed funds per repository",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    CURRENT_DATE,\n    SUM(\"Total contribution\") AS \"Total funds\",\n    \"Repository name\",\n    \"Currency\"\nFROM\n    (\n        SELECT\n            r.name AS \"Repository name\",\n            dc.currency AS \"Currency\",\n            SUM(CASE WHEN dc.currency = 'USD' THEN dc.balance / (10^6)\n                     WHEN dc.currency = 'GAS' THEN dc.balance / (10^8)\n                     WHEN dc.currency = 'ETH' THEN dc.balance / (10^18)\n                     ELSE dc.balance END) AS \"Total contribution\"\n        FROM\n            daily_contribution dc\n            INNER JOIN repo r ON dc.repo_id = r.id\n        GROUP BY\n            r.name,\n            dc.currency\n\n        UNION ALL\n\n        SELECT\n            r.name AS \"Repository name\",\n            fc.currency AS \"Currency\",\n            SUM(CASE WHEN fc.currency = 'USD' THEN fc.balance / (10^6)\n                     WHEN fc.currency = 'GAS' THEN fc.balance / (10^8)\n                     WHEN fc.currency = 'ETH' THEN fc.balance / (10^18)\n                     ELSE fc.balance END) AS \"Total contribution\"\n        FROM\n            future_contribution fc\n            INNER JOIN repo r ON fc.repo_id = r.id\n        GROUP BY\n            r.name,\n            fc.currency\n    ) AS combined_contributions\nGROUP BY\n    CURRENT_DATE,\n    \"Repository name\",\n    \"Currency\"\nORDER BY\n    CURRENT_DATE,\n    \"Repository name\",\n    \"Currency\";\n"
    }
   ]
  },
  {
   "title": "Remaining balance on payout contracts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "flatfeestack_eth_payout_remaining_balance",
     "legendFormat": "__auto"
    },
    {
     "expr": "flatfeestack_usdc_payout_remaining_balance",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "New users today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM users WHERE created_at::date = CURRENT_DATE;"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Active users",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(DATE_TRUNC('day', time), 'YYYY-MM-DD'),\n       SUM(users) OVER (ORDER BY time) AS active_users\nFROM (SELECT DATE_TRUNC('day', created_at) AS time,\n             COUNT(*)                      AS users\n      FROM users\n      GROUP BY 1) AS user_counts\nORDER BY time ASC\nLIMIT 10"
    }
   ]
  }
 ]
}