export const MembershipABI = [
  "event ChangeInChairman(address indexed concernedChairman, bool removedOrAdded)",
  "event ChangeInMembershipStatus(address indexed accountAddress, uint256 indexed currentStatus)",
  "event DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate)",
  "event DelegateVotesChanged(address indexed delegate, uint256 previousBalance, uint256 newBalance)",
  "event Initialized(uint8 version)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function addChairman(address _adr) returns (bool)",
  "function approveMembership(address _adr) returns (bool)",
  "function chairmen(uint256) view returns (address)",
  "function delegate(address delegatee)",
  "function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s)",
  "function delegates(address account) pure returns (address)",
  "function getChairmenLength() view returns (uint256)",
  "function getFirstApproval(address _adr) view returns (address)",
  "function getMembersLength() view returns (uint256)",
  "function getMembershipStatus(address _adr) view returns (uint256)",
  "function getPastTotalSupply(uint256 blockNumber) view returns (uint256)",
  "function getPastVotes(address account, uint256 blockNumber) view returns (uint256)",
  "function getVotes(address account) view returns (uint256)",
  "function initialize(address _firstChairman, address _secondChairman, address _walletContract)",
  "function isChairman(address _adr) view returns (bool)",
  "function members(uint256) view returns (address)",
  "function membershipFee() view returns (uint256)",
  "function minimumChairmen() view returns (uint256)",
  "function nextMembershipFeePayment(address) view returns (uint256)",
  "function owner() view returns (address)",
  "function payMembershipFee() payable",
  "function removeChairman(address _adr) returns (bool)",
  "function removeMember(address _adr)",
  "function removeMembersThatDidntPay()",
  "function renounceOwnership()",
  "function requestMembership() returns (bool)",
  "function setMembershipFee(uint256 newMembershipFee)",
  "function transferOwnership(address newOwner)",
];
