export const MembershipABI = [
  "event ChangeInChairman(address indexed concernedChairman, bool removedOrAdded)",
  "event ChangeInMembershipStatus(address indexed accountAddress, uint256 indexed currentStatus)",
  "event ChangeInWhiteLister(address indexed concernedWhitelister, bool removedOrAdded)",
  "event DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate)",
  "event DelegateVotesChanged(address indexed delegate, uint256 previousBalance, uint256 newBalance)",
  "event Initialized(uint8 version)",
  "function addWhitelister(address _adr) returns (bool)",
  "function chairman() view returns (address)",
  "function delegate(address delegatee)",
  "function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s)",
  "function delegates(address account) pure returns (address)",
  "function getFirstWhitelister(address _adr) view returns (address)",
  "function getMembersLength() view returns (uint256)",
  "function getMembershipStatus(address _adr) view returns (uint256)",
  "function getPastTotalSupply(uint256 blockNumber) view returns (uint256)",
  "function getPastVotes(address account, uint256 blockNumber) view returns (uint256)",
  "function getVotes(address account) view returns (uint256)",
  "function initialize(address _chairman, address _whitelisterOne, address _whitelisterTwo, address _walletContract)",
  "function isWhitelister(address _adr) view returns (bool)",
  "function members(uint256) view returns (address)",
  "function membershipFee() view returns (uint256)",
  "function minimumWhitelister() view returns (uint256)",
  "function nextMembershipFeePayment(address) view returns (uint256)",
  "function payMembershipFee() payable",
  "function removeMember(address _adr)",
  "function removeMembersThatDidntPay()",
  "function removeWhitelister(address _adr) returns (bool)",
  "function requestMembership() returns (bool)",
  "function setChairman(address _adr) returns (bool)",
  "function setMembershipFee(uint256 newMembershipFee)",
  "function whitelistMember(address _adr) returns (bool)",
  "function whitelisterList(uint256) view returns (address)",
  "function whitelisterListLength() view returns (uint256)",
];
