// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Comment defines model for Comment.
type Comment struct {
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// CommentInput defines model for CommentInput.
type CommentInput struct {
	Content string `json:"content"`
}

// Post defines model for Post.
type Post struct {
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Open      bool               `json:"open"`
	Title     string             `json:"title"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// PostInput defines model for PostInput.
type PostInput struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// CommentId defines model for CommentId.
type CommentId = openapi_types.UUID

// PostId defines model for PostId.
type PostId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error string `json:"error"`
}

// Forbidden defines model for Forbidden.
type Forbidden struct {
	Error string `json:"error"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error string `json:"error"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized struct {
	Error string `json:"error"`
}

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostInput

// PostPostsPostIdCommentsJSONRequestBody defines body for PostPostsPostIdComments for application/json ContentType.
type PostPostsPostIdCommentsJSONRequestBody = CommentInput

// PutPostsPostIdCommentsJSONRequestBody defines body for PutPostsPostIdComments for application/json ContentType.
type PutPostsPostIdCommentsJSONRequestBody = PostInput

// PutPostsPostIdCommentsCommentIdJSONRequestBody defines body for PutPostsPostIdCommentsCommentId for application/json ContentType.
type PutPostsPostIdCommentsCommentIdJSONRequestBody = CommentInput
