// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all posts
	// (GET /posts)
	GetPosts(w http.ResponseWriter, r *http.Request)
	// Create a new post
	// (POST /posts)
	PostPosts(w http.ResponseWriter, r *http.Request)
	// Delete a Post
	// (DELETE /posts/{postId})
	DeletePostsPostId(w http.ResponseWriter, r *http.Request, postId PostId)
	// Get a specific post
	// (GET /posts/{postId})
	GetPostsPostId(w http.ResponseWriter, r *http.Request, postId PostId)
	// Get all comments
	// (GET /posts/{postId}/comments)
	GetPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId)
	// Add a comment to a post
	// (POST /posts/{postId}/comments)
	PostPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId)
	// Update a post
	// (PUT /posts/{postId}/comments)
	PutPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId)
	// Delete a comment
	// (DELETE /posts/{postId}/comments/{commentId})
	DeletePostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId PostId, commentId CommentId)
	// Update a comment
	// (PUT /posts/{postId}/comments/{commentId})
	PutPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId PostId, commentId CommentId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetPosts operation middleware
func (siw *ServerInterfaceWrapper) GetPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPosts(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"User"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPosts(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeletePostsPostId operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsPostId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"Admin"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePostsPostId(w, r, postId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPostId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPostId(w, r, postId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPostsPostIdComments operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPostIdComments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPostIdComments(w, r, postId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostPostsPostIdComments operation middleware
func (siw *ServerInterfaceWrapper) PostPostsPostIdComments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"User"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPostsPostIdComments(w, r, postId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PutPostsPostIdComments operation middleware
func (siw *ServerInterfaceWrapper) PutPostsPostIdComments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"User"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostsPostIdComments(w, r, postId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeletePostsPostIdCommentsCommentId operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "commentId" -------------
	var commentId CommentId

	err = runtime.BindStyledParameter("simple", false, "commentId", mux.Vars(r)["commentId"], &commentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commentId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"Admin"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePostsPostIdCommentsCommentId(w, r, postId, commentId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PutPostsPostIdCommentsCommentId operation middleware
func (siw *ServerInterfaceWrapper) PutPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameter("simple", false, "postId", mux.Vars(r)["postId"], &postId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "commentId" -------------
	var commentId CommentId

	err = runtime.BindStyledParameter("simple", false, "commentId", mux.Vars(r)["commentId"], &commentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commentId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"User"})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostsPostIdCommentsCommentId(w, r, postId, commentId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/posts", wrapper.GetPosts).Methods("GET")

	r.HandleFunc(options.BaseURL+"/posts", wrapper.PostPosts).Methods("POST")

	r.HandleFunc(options.BaseURL+"/posts/{postId}", wrapper.DeletePostsPostId).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/posts/{postId}", wrapper.GetPostsPostId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/posts/{postId}/comments", wrapper.GetPostsPostIdComments).Methods("GET")

	r.HandleFunc(options.BaseURL+"/posts/{postId}/comments", wrapper.PostPostsPostIdComments).Methods("POST")

	r.HandleFunc(options.BaseURL+"/posts/{postId}/comments", wrapper.PutPostsPostIdComments).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/posts/{postId}/comments/{commentId}", wrapper.DeletePostsPostIdCommentsCommentId).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/posts/{postId}/comments/{commentId}", wrapper.PutPostsPostIdCommentsCommentId).Methods("PUT")

	return r
}

type BadRequestJSONResponse struct {
	Error string `json:"error"`
}

type ForbiddenJSONResponse struct {
	Error string `json:"error"`
}

type InternalServerErrorResponse struct {
}

type NoContentJSONResponse struct {
	Info *string `json:"info,omitempty"`
}

type NotFoundJSONResponse struct {
	Error string `json:"error"`
}

type UnauthorizedJSONResponse struct {
	Error string `json:"error"`
}

type GetPostsRequestObject struct {
}

type GetPostsResponseObject interface {
	VisitGetPostsResponse(w http.ResponseWriter) error
}

type GetPosts200JSONResponse []Post

func (response GetPosts200JSONResponse) VisitGetPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPosts204JSONResponse struct{ NoContentJSONResponse }

func (response GetPosts204JSONResponse) VisitGetPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type GetPosts500Response = InternalServerErrorResponse

func (response GetPosts500Response) VisitGetPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostPostsRequestObject struct {
	Body *PostPostsJSONRequestBody
}

type PostPostsResponseObject interface {
	VisitPostPostsResponse(w http.ResponseWriter) error
}

type PostPosts201JSONResponse Post

func (response PostPosts201JSONResponse) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostPosts400JSONResponse struct{ BadRequestJSONResponse }

func (response PostPosts400JSONResponse) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostPosts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostPosts401JSONResponse) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostPosts500Response = InternalServerErrorResponse

func (response PostPosts500Response) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type DeletePostsPostIdRequestObject struct {
	PostId PostId `json:"postId"`
}

type DeletePostsPostIdResponseObject interface {
	VisitDeletePostsPostIdResponse(w http.ResponseWriter) error
}

type DeletePostsPostId200Response struct {
}

func (response DeletePostsPostId200Response) VisitDeletePostsPostIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeletePostsPostId204JSONResponse struct{ NoContentJSONResponse }

func (response DeletePostsPostId204JSONResponse) VisitDeletePostsPostIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeletePostsPostId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePostsPostId401JSONResponse) VisitDeletePostsPostIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostIdRequestObject struct {
	PostId PostId `json:"postId"`
}

type GetPostsPostIdResponseObject interface {
	VisitGetPostsPostIdResponse(w http.ResponseWriter) error
}

type GetPostsPostId200JSONResponse Post

func (response GetPostsPostId200JSONResponse) VisitGetPostsPostIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostId404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPostsPostId404JSONResponse) VisitGetPostsPostIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostId500Response = InternalServerErrorResponse

func (response GetPostsPostId500Response) VisitGetPostsPostIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetPostsPostIdCommentsRequestObject struct {
	PostId PostId `json:"postId"`
}

type GetPostsPostIdCommentsResponseObject interface {
	VisitGetPostsPostIdCommentsResponse(w http.ResponseWriter) error
}

type GetPostsPostIdComments200JSONResponse []Comment

func (response GetPostsPostIdComments200JSONResponse) VisitGetPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostIdComments204JSONResponse struct{ NoContentJSONResponse }

func (response GetPostsPostIdComments204JSONResponse) VisitGetPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostIdComments404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPostsPostIdComments404JSONResponse) VisitGetPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsPostIdComments500Response = InternalServerErrorResponse

func (response GetPostsPostIdComments500Response) VisitGetPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostPostsPostIdCommentsRequestObject struct {
	PostId PostId `json:"postId"`
	Body   *PostPostsPostIdCommentsJSONRequestBody
}

type PostPostsPostIdCommentsResponseObject interface {
	VisitPostPostsPostIdCommentsResponse(w http.ResponseWriter) error
}

type PostPostsPostIdComments201JSONResponse Comment

func (response PostPostsPostIdComments201JSONResponse) VisitPostPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostPostsPostIdComments400JSONResponse struct{ BadRequestJSONResponse }

func (response PostPostsPostIdComments400JSONResponse) VisitPostPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostPostsPostIdComments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostPostsPostIdComments401JSONResponse) VisitPostPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsRequestObject struct {
	PostId PostId `json:"postId"`
	Body   *PutPostsPostIdCommentsJSONRequestBody
}

type PutPostsPostIdCommentsResponseObject interface {
	VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error
}

type PutPostsPostIdComments200JSONResponse Post

func (response PutPostsPostIdComments200JSONResponse) VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdComments400JSONResponse struct{ BadRequestJSONResponse }

func (response PutPostsPostIdComments400JSONResponse) VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdComments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutPostsPostIdComments401JSONResponse) VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdComments403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutPostsPostIdComments403JSONResponse) VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdComments404JSONResponse struct{ NotFoundJSONResponse }

func (response PutPostsPostIdComments404JSONResponse) VisitPutPostsPostIdCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeletePostsPostIdCommentsCommentIdRequestObject struct {
	PostId    PostId    `json:"postId"`
	CommentId CommentId `json:"commentId"`
}

type DeletePostsPostIdCommentsCommentIdResponseObject interface {
	VisitDeletePostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error
}

type DeletePostsPostIdCommentsCommentId204Response struct {
}

func (response DeletePostsPostIdCommentsCommentId204Response) VisitDeletePostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePostsPostIdCommentsCommentId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePostsPostIdCommentsCommentId401JSONResponse) VisitDeletePostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeletePostsPostIdCommentsCommentId403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeletePostsPostIdCommentsCommentId403JSONResponse) VisitDeletePostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsCommentIdRequestObject struct {
	PostId    PostId    `json:"postId"`
	CommentId CommentId `json:"commentId"`
	Body      *PutPostsPostIdCommentsCommentIdJSONRequestBody
}

type PutPostsPostIdCommentsCommentIdResponseObject interface {
	VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error
}

type PutPostsPostIdCommentsCommentId200JSONResponse Comment

func (response PutPostsPostIdCommentsCommentId200JSONResponse) VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsCommentId400JSONResponse struct{ BadRequestJSONResponse }

func (response PutPostsPostIdCommentsCommentId400JSONResponse) VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsCommentId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutPostsPostIdCommentsCommentId401JSONResponse) VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsCommentId403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutPostsPostIdCommentsCommentId403JSONResponse) VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsPostIdCommentsCommentId404JSONResponse struct{ NotFoundJSONResponse }

func (response PutPostsPostIdCommentsCommentId404JSONResponse) VisitPutPostsPostIdCommentsCommentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all posts
	// (GET /posts)
	GetPosts(ctx context.Context, request GetPostsRequestObject) (GetPostsResponseObject, error)
	// Create a new post
	// (POST /posts)
	PostPosts(ctx context.Context, request PostPostsRequestObject) (PostPostsResponseObject, error)
	// Delete a Post
	// (DELETE /posts/{postId})
	DeletePostsPostId(ctx context.Context, request DeletePostsPostIdRequestObject) (DeletePostsPostIdResponseObject, error)
	// Get a specific post
	// (GET /posts/{postId})
	GetPostsPostId(ctx context.Context, request GetPostsPostIdRequestObject) (GetPostsPostIdResponseObject, error)
	// Get all comments
	// (GET /posts/{postId}/comments)
	GetPostsPostIdComments(ctx context.Context, request GetPostsPostIdCommentsRequestObject) (GetPostsPostIdCommentsResponseObject, error)
	// Add a comment to a post
	// (POST /posts/{postId}/comments)
	PostPostsPostIdComments(ctx context.Context, request PostPostsPostIdCommentsRequestObject) (PostPostsPostIdCommentsResponseObject, error)
	// Update a post
	// (PUT /posts/{postId}/comments)
	PutPostsPostIdComments(ctx context.Context, request PutPostsPostIdCommentsRequestObject) (PutPostsPostIdCommentsResponseObject, error)
	// Delete a comment
	// (DELETE /posts/{postId}/comments/{commentId})
	DeletePostsPostIdCommentsCommentId(ctx context.Context, request DeletePostsPostIdCommentsCommentIdRequestObject) (DeletePostsPostIdCommentsCommentIdResponseObject, error)
	// Update a comment
	// (PUT /posts/{postId}/comments/{commentId})
	PutPostsPostIdCommentsCommentId(ctx context.Context, request PutPostsPostIdCommentsCommentIdRequestObject) (PutPostsPostIdCommentsCommentIdResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetPosts operation middleware
func (sh *strictHandler) GetPosts(w http.ResponseWriter, r *http.Request) {
	var request GetPostsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPosts(ctx, request.(GetPostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPosts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPostsResponseObject); ok {
		if err := validResponse.VisitGetPostsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// PostPosts operation middleware
func (sh *strictHandler) PostPosts(w http.ResponseWriter, r *http.Request) {
	var request PostPostsRequestObject

	var body PostPostsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPosts(ctx, request.(PostPostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPosts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPostsResponseObject); ok {
		if err := validResponse.VisitPostPostsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// DeletePostsPostId operation middleware
func (sh *strictHandler) DeletePostsPostId(w http.ResponseWriter, r *http.Request, postId PostId) {
	var request DeletePostsPostIdRequestObject

	request.PostId = postId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePostsPostId(ctx, request.(DeletePostsPostIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePostsPostId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePostsPostIdResponseObject); ok {
		if err := validResponse.VisitDeletePostsPostIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetPostsPostId operation middleware
func (sh *strictHandler) GetPostsPostId(w http.ResponseWriter, r *http.Request, postId PostId) {
	var request GetPostsPostIdRequestObject

	request.PostId = postId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPostsPostId(ctx, request.(GetPostsPostIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPostsPostId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPostsPostIdResponseObject); ok {
		if err := validResponse.VisitGetPostsPostIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetPostsPostIdComments operation middleware
func (sh *strictHandler) GetPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId) {
	var request GetPostsPostIdCommentsRequestObject

	request.PostId = postId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPostsPostIdComments(ctx, request.(GetPostsPostIdCommentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPostsPostIdComments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPostsPostIdCommentsResponseObject); ok {
		if err := validResponse.VisitGetPostsPostIdCommentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// PostPostsPostIdComments operation middleware
func (sh *strictHandler) PostPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId) {
	var request PostPostsPostIdCommentsRequestObject

	request.PostId = postId

	var body PostPostsPostIdCommentsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPostsPostIdComments(ctx, request.(PostPostsPostIdCommentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPostsPostIdComments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPostsPostIdCommentsResponseObject); ok {
		if err := validResponse.VisitPostPostsPostIdCommentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// PutPostsPostIdComments operation middleware
func (sh *strictHandler) PutPostsPostIdComments(w http.ResponseWriter, r *http.Request, postId PostId) {
	var request PutPostsPostIdCommentsRequestObject

	request.PostId = postId

	var body PutPostsPostIdCommentsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutPostsPostIdComments(ctx, request.(PutPostsPostIdCommentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutPostsPostIdComments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutPostsPostIdCommentsResponseObject); ok {
		if err := validResponse.VisitPutPostsPostIdCommentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// DeletePostsPostIdCommentsCommentId operation middleware
func (sh *strictHandler) DeletePostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId PostId, commentId CommentId) {
	var request DeletePostsPostIdCommentsCommentIdRequestObject

	request.PostId = postId
	request.CommentId = commentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePostsPostIdCommentsCommentId(ctx, request.(DeletePostsPostIdCommentsCommentIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePostsPostIdCommentsCommentId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePostsPostIdCommentsCommentIdResponseObject); ok {
		if err := validResponse.VisitDeletePostsPostIdCommentsCommentIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// PutPostsPostIdCommentsCommentId operation middleware
func (sh *strictHandler) PutPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId PostId, commentId CommentId) {
	var request PutPostsPostIdCommentsCommentIdRequestObject

	request.PostId = postId
	request.CommentId = commentId

	var body PutPostsPostIdCommentsCommentIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutPostsPostIdCommentsCommentId(ctx, request.(PutPostsPostIdCommentsCommentIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutPostsPostIdCommentsCommentId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutPostsPostIdCommentsCommentIdResponseObject); ok {
		if err := validResponse.VisitPutPostsPostIdCommentsCommentIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX2/bNhD/KsRtj1yltOmL3hx3GbwNmbEu2EMQDIx0jllIIktR7TxD330gqb+WElmJ",
	"47hAXwJTuiN/97u/YrYQikSKFFOdQbAFyRRLUKOyq7lIEkz1IjKLCLNQcam5SCGAxQciVkSvkYROCChw",
	"80IyvQYKKUsQAgjrHSgo/JxzhREEWuVIIQvXmDCz9UqohGkIIM+5kdQbaZQzrXh6D0VBYSmyERhSZA9g",
	"kE73OQAKo5xJkWZoiblg0Z/4OcdMm1UoUm0YCLbApIx5yAw671NmIG5bx0glJCrN3SaolFDmR9/cBulN",
	"KXZbgxJ3nzDUDlSXjAsWkQpWQeFSqDseRZieEsYGVEFhkWpUKYs/ovqC6ufqrB0Xl0LESREnVlC4EvPG",
	"qCfax9OVGDZv1JIrQarzLRh9KfI0OiWur4QmDlRB4TpluV4Lxf/DkwLZwWVeu5Pb9aePwqnskbm0bWf/",
	"nUKmMfqH6c5WEdP4k+YJDu3Ho72OzWU0cesdBu22FXhaWdzB3KeX1iU7lfkAby0yEvbv75je6zUE732f",
	"QsLTan02hq3aZgiAqdTfosOEdIWyfHEnRIzMVinNdYyDcA7jZLf/mLNLhA9RPsnhZ/6ox1tmdxWnRcqu",
	"bQMVgUKGYa643nw0me9w3yFTqGa5OaRaXVb8/vr3X1DWCesq+7bheq21dJWmqu7dijNbLshKKMLM3zwh",
	"mVjpr0xh7QrbpfKEzJYLoPAFVeYUz974b/wqVpjkEMA7+4jaicMC98y0YX/do6XdeMOWVjO+wC+ol1Zg",
	"Z6B46/uTijLXmFjFHxWuIIAfvGaO88oK6tlUbFoZU4pthkrwH78Zqbf++UMb1lC9pucWFN470I9rDPV4",
	"6/Q8SZjaOE4Ii2PimCuoHdj61BlrGu7slHMhos0k2sbYcllUdKPYDItFz19nBz14yC1zl/yGkfN9mG4N",
	"pVblbFyl23yf69EyjSG46SbwDVxnqOC2uG273ZlHGEnxq5vezSYuf7ytG9oLl70xauwHxAf73IbEshrx",
	"298vN8OGNCJeqWZwDWXjYbLkCY54nMxZlPB0l01HBmFk6b6DNLvP2sL08Xr0MgS+aHo4f5zv5w9dz8GH",
	"LFokkxjyFQ8fjF+v/AAe7wiOynkl/lqe2KuxVHP5C/aWV/VrHJPab+P96JCeO3xb63wQHLmz1XFyAs1t",
	"eoOaRRFhVSAQLQgr05xCOWvvBET+LcTDxDHneHX8OBPOuf9uXKlzSTWxEk2Ps2v7FVlH1yNNxNvW96nT",
	"JqMqGOet69inRSUdlWzOGGhG5/25qnuPdhSnPme+aq67+yPWhLLwGp44hebiH6O5fC8pVUkJ2yRldupx",
	"QZarGALwmOQ2OMpY7l2V2NCu/5PilsVt8X8AAAD//z580Bg3GgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
