FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat brotli gzip zstd parallel
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml rsbuild.config.ts ssr.mjs tsconfig.json ./
RUN pnpm install
ENTRYPOINT ["pnpm", "run", "dev"]