global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: database
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: analyzer
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9083"]
        labels:
          hostname: 'go-analyzer-server'
          service: 'analyzer'
  - job_name: auth
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:9081" ]
        labels:
          hostname: 'go-auth-server'
          service: 'auth'
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9082"]
        labels:
          hostname: 'go-backend-server'
          service: 'backend'
  - job_name: forum
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9086"]
        labels:
          hostname: 'go-forum-server'
          service: 'forum'
  - job_name: payout
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:9084" ]
        labels:
          hostname: 'go-payout-server'
          service: 'payout'