name: publish zip to flatfeestack

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2 #checkout to $GITHUB_WORKSPACE
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - shell: bash
        env:
          TOKEN: ${{ secrets.WWW_TOKEN }}
        run: |
          'npm install'
          'npm run build'
          'tar cvfz /tmp/upload.tar.gz public/*'
          'curl -H "Authorization: Bearer ${TOKEN}" -X POST -F "upload=@/tmp/upload.tar.gz" https://flatfeestack.io/upload'