name: Test and build analyzer

on:
  push:
    paths:
      - ".github/workflows/analyzer.yaml"
      - "analyzer/**"
  pull_request:
    paths:
      - ".github/workflows/analyzer.yaml"
      - "analyzer/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test container
        uses: docker/build-push-action@v4
        with:
          context: analyzer
          load: true
          target: builder
          tags: analyzer

      - name: Run tests
        run: |
          docker run -v $(pwd)/analyzer:/app --rm analyzer go test -v ./...

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: analyzer
          load: true
          tags: analyzer

      - name: Run analyzer
        run: docker run --env-file analyzer/.example.env --rm -d -p 9083:9083 analyzer

      - name: Check if analyzer is reachable
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 5
          command: curl -v localhost:9083
