name: Test and build analyzer

on:
  push:
    paths:
      - ".github/workflows/analyzer.yaml"
      - "analyzer/**"
  pull_request:
    paths:
      - ".github/workflows/analyzer.yaml"
      - "analyzer/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test container
        uses: docker/build-push-action@v4
        with:
          context: analyzer
          load: true
          target: builder
          tags: ghcr.io/flatfeestack/flatfeestack/analyzer:test

      - name: Run tests
        run: |
          docker run -v $(pwd)/analyzer:/app --rm ghcr.io/flatfeestack/flatfeestack/analyzer:test go test -v ./...

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: analyzer
          load: true
          tags: ghcr.io/flatfeestack/flatfeestack/analyzer:test

      - name: Run analyzer
        run: docker run --env-file analyzer/.example.env --rm -d -p 9083:9083 ghcr.io/flatfeestack/flatfeestack/analyzer:test

      - name: Check if analyzer is reachable
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 5
          command: curl -v localhost:9083

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/flatfeestack/flatfeestack/analyzer
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Push
        uses: docker/build-push-action@v4
        with:
          context: analyzer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
