name: Test and build auth

on:
  push:
    paths:
      - ".github/workflows/auth.yaml"
      - "../../auth/**"
  pull_request:
    paths:
      - ".github/workflows/auth.yaml"
      - "../../auth/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test container
        uses: docker/build-push-action@v4
        with:
          context: auth
          load: true
          target: builder
          tags: auth

      - name: Run tests
        run: |
          docker run -v $(pwd)/auth:/app --rm auth go test -v ./...

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: auth
          load: true
          tags: auth

      - name: Run Postgres server for testing
        run: docker run --env-file db/.example.env -p 5432:5432 -d postgres:15-alpine

      - name: Run auth
        run: docker run --env-file auth/.example.env -d --network="host" -e DB_PATH=postgresql://postgres:password@127.0.0.1:5432/flatfeestack?sslmode=disable auth

      - name: Check if auth is reachable
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 5
          command: curl -v localhost:9081
