name: TEST-build-and-push

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TAG_IMAGE: latest-test
    steps:
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CR_PAT_TOKEN }}
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT_TOKEN }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FLATFEESTACK_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Update (fetch micro-services)
        run: bash update.sh
      - name: Debug
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml config
      - name: Pull Current Images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml pull || true
      - name: Build Images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - name: Push Images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml push
      - name: Deploy - TEST
        run: DOCKER_HOST="ssh://sibex@axelra.net:2222" docker stack deploy -c docker-compose.yml -c docker-compose.test.yml flatfee --with-registry-auth
