name: build-and-push

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'
        default: 'false'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CR_PAT_TOKEN }}
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT_TOKEN }}
      - name: Pull Current Images
        run: docker-compose pull || true
      - name: Build Images
        run: docker-compose build
      - name: Push Images
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master') && github.event.inputs.deploy == 'true'
        run: docker-compose push
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master') && github.event.inputs.deploy == 'true'
        with:
          command: |
            cd flatfeestack
            docker-compose -f docker-compose.test.yml --env-file .test.env up -d
          host: ${{ secrets.FLATFEESTACK1_NODE_HOST }}
          username: ubuntu
          privateKey: ${{ secrets.FLATFEESTACK1_NODE_PRIVATE_KEY}}