name: build-and-push

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push Images?'
        default: 'false'
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT_TOKEN }}
      - name: Pull Current Images
        run: docker-compose pull || true
      - name: Build Images
        run: docker-compose build
      - name: Push Images
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master') && github.event.inputs.push == 'true'
        run: docker-compose push