name: TEST-build-and-push

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TAG_IMAGE: latest-test
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CR_PAT_TOKEN }}
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT_TOKEN }}
      - name: Pull Current Images
        run: docker-compose -f docker-compose.build.yml pull || true
      - name: Build Images
        run: docker-compose -f docker-compose.build.yml build
      - name: Push Images
        run: docker-compose -f docker-compose.build.yml push
      - name: Deploy - TEST
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sh docker_login.sh && cd flatfeestack && git pull --recurse-submodules && TAG_IMAGE=${{ env.TAG_IMAGE }} docker-compose -f docker-compose.test.yml -f docker-compose.caddy.yml --env-file .test.env pull && TAG_IMAGE=${{ env.TAG_IMAGE }} docker-compose -f docker-compose.test.yml -f docker-compose.caddy.yml --env-file .test.env up -d
          host: ${{ secrets.FLATFEESTACK1_NODE_HOST }}
          username: ubuntu
          privateKey: ${{ secrets.FLATFEESTACK1_NODE_PRIVATE_KEY}}
