name: Validate Renovate configuration

on:
  push:
    paths:
      - ".github/workflows/renovate-config-validation.yaml"
      - "renovate.json"
  pull_request:
    paths:
      - ".github/workflows/renovate-config-validation.yaml"
      - "renovate.json"
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.0
        with:
          pattern: "*.json" # Regular expression for filename to validate, default to *.json
