name: Test ETH smart contracts

on:
  push:
    paths:
      - ".github/workflows/smart-contracts-eth.yaml"
      - "smart-contracts-eth/**"
  pull_request:
    paths:
      - ".github/workflows/smart-contracts-eth.yaml"
      - "smart-contracts-eth/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contracts-eth
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "smart-contracts-eth/.nvmrc"
          cache: "npm"
          cache-dependency-path: smart-contracts-eth/package-lock.json
      - run: npm i
      - run: npm run prettify:check
      - run: npm run lint
      - run: npm run hardhat:coverage
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: smart-contracts-eth/coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
